### ISSUE TITLE
need to update firestore dependency

### ISSUE THREAD

**Issue by xmany** [DarshanGowda0/GeoFlutterFire#157]
Because `geoflutterfire 3.0.0-nullsafety.2` depends on `cloud_firestore ^1.0.0` and no versions of `geoflutterfire match >3.0.0-nullsafety.2 <4.0.0`, `geoflutterfire ^3.0.0-nullsafety.2` requires `cloud_firestore ^1.0.0.`

So, because myApp depends on both `cloud_firestore ^2.0.0` and `geoflutterfire ^3.0.0-nullsafety.2`, version solving failed.
pub get failed (1; So, because icoffee depends on both cloud_firestore ^2.0.0 and geoflutterfire ^3.0.0-nullsafety.2, version solving failed.)
exit code 1

**Comment by awaik** [comment]
Solved by your PR :) 
https://github.com/DarshanGowda0/GeoFlutterFire/pull/158

**Comment by cybertheory** [comment]
There is another issue:

'''
../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/geoflutterfire-2.2.2/lib/src/collection.dart:108:56: Error: The operator '[]' isn't defined for the class 'Object'.
 - 'Object' is from 'dart:core'.
Try correcting the operator to an existing operator, or defining a '[]' operator.
            distanceDocSnapshot.documentSnapshot.data()[fieldList[0]];
'''
            
Why is data's fields being accessed instead of the documentStapshot's? The new firestore version 2.2.0 sets .data()'s return type as an object not a Map.
