### ISSUE TITLE
Cloud Firestore version Mismatch

### ISSUE THREAD

**Issue by debottam31** [DarshanGowda0/GeoFlutterFire#40]
Because geoflutterfire >=2.0.3+3 depends on cloud_firestore ^0.10.1 and test_app depends on cloud_firestore ^0.11.0+1, geoflutterfire >=2.0.3+3 is forbidden.

**Comment by debottam31** [comment]
Need this fix bit early, if possible please update the package. Thanks!! Or let me know if i can raise a PR.

**Comment by DarshanGowda0** [comment]
@debottam31 Yes, you can upgrade and raise a PR!

**Comment by FredvanRijswijk** [comment]
#41 raised @DarshanGowda0

**Comment by DarshanGowda0** [comment]
Thanks @FredvanRijswijk 😄

**Comment by rdev-software** [comment]
Raise again pls: Because geoflutterfire 2.0.3+4 depends on cloud_firestore ^0.11.0+1 and no versions of geoflutterfire match >2.0.3+4 <3.0.0, geoflutterfire ^2.0.3+4 requires cloud_firestore ^0.11.0+1.
So, because bigrush depends on both cloud_firestore ^0.12.1 and geoflutterfire ^2.0.3+4, version solving failed.
pub get failed (1)
